# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170404_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
