# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170410_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug-<built-in function id>', unique=True),
        ),
    ]
