# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='Slug'),
        ),
    ]
