# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170410_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Title', max_length=120),
        ),
    ]
