# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170411_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
    ]
