# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 19:44
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170411_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
